name: Docker Image Publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag resep98/nginx-spa-minimal:latest
    - name: Publish the Docker image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: resep98/nginx-spa-minimal:latest
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
